"""empty message

Revision ID: 2aead359aedb
Revises: 
Create Date: 2018-06-02 01:05:13.128276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aead359aedb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_identities', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_index('index_on_user_id_v3_user_identity', table_name='author_identities')
    op.drop_column('author_identities', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_identities', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('index_on_user_id_v3_user_identity', 'author_identities', ['user_id'], unique=False)
    op.drop_column('author_identities', 'password')
    # ### end Alembic commands ###
