"""empty message

Revision ID: 36e98eb6031f
Revises: e83decce1e3c
Create Date: 2018-06-02 02:38:33.793504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e98eb6031f'
down_revision = 'e83decce1e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_identities', sa.Column('name', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_identities', 'name')
    # ### end Alembic commands ###
