"""empty message

Revision ID: e83decce1e3c
Revises: 2aead359aedb
Create Date: 2018-06-02 01:55:09.745685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83decce1e3c'
down_revision = '2aead359aedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories_library', sa.Column('row_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories_library', 'row_status')
    # ### end Alembic commands ###
